# -*- coding: utf-8 -*-
"""*args and **kwargs explained.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kI9Df71BXdRxqwto37DZEheLPK5OILlf

-  ***args** is used to pass a variable-length argument
- this is non-keyword

- ****kwargs** is used to pass a variable-length argument
- this key-word
"""

def printnum(*args):
  for i in args:
    print(i)

printnum([1,2,3])

printnum(*[1,2,3])

def printdetail(**kwargs):
  for i in kwargs:
    print(i,":",kwargs[i])

printdetail(name="joe",age=19)